### ISSUE TITLE
Плиз хелп

### ISSUE THREAD

**Issue by pcadminby** [SergejPr/HomeAssistance-NooLite#13]
Добрый день.
Я совсем недавно изучаю HomeAssistance
Не могли бы Вы поделится инструкцией как установить Ваш плагин.. 
а то я его и так и эток.. ничего не получается. 
Заранее спасибо .

**Comment by tenens-fusum** [comment]
Устанавливал следующим образом:
1. Создал папку custom_components в папке, где находится файлы конфигурации HA (configuration.yaml итд)
2. В нее скопировал папку noolite (https://github.com/SergejPr/HomeAssistance-NooLite/tree/master/custom_components/noolite)
3. Насколько я понял были проблемы с правами, поэтому chmod 777
4. В configuration.yaml добавил (У меня USB стик): 
`noolite:
  port: "/dev/ttyUSB0"`
5. Добавил устройства в lights.yaml 
`- platform: noolite
  channel: 19
  name: "Hall_light"
  scan_interval: 56
  mode: noolite-f
  friendly_name: Свет в гостиной`
6. Устройства прописывал к стику через Noolite ONE переключая стик в виндовую машину. (Как вариант инструкции https://sprut.ai/client/article/615)

**Comment by SergejPr** [comment]
Добрый день, извиняюсь что не ответил раньше - не было возможности. Выше уже привели инструкцию как устанавливается компонент.

**Comment by pcadminby** [comment]
Спасибо огромное.

**Comment by SergejPr** [comment]
Обновил README. Теперь оно более информативное.
