### ISSUE TITLE
Не работает кнопка PU-313

### ISSUE THREAD

**Issue by eratnik** [SergejPr/HomeAssistance-NooLite#15]
Пульт PU-313 привязан к каналам 3 и 4
Пробовал прописывать их как binary_sensor и как sensor - объекты в HA появляются, но никаких событий или смены состояний не происходит. Если заводить как binary_sensor состояние off и не меняется.
При этом силовые блоки настроены как light и отлично управляются.
```
  - name: "Кнопка noolite вверх на кухне"
    platform: noolite
    channel: 3
    type: remote
   - name: "Кнопка noolite вниз  на кухне"
    platform: noolite
    channel: 4
    type: remote
```
Может быть у вас будут мысли в какую сторону можно копать? Уже замаялся я с этими выключателями и почти созрел, чтобы отказаться от них

**Comment by SergejPr** [comment]
Добрый день, 

На данный момент логика работы с пультами построена таким образом, что состояние держится примерно 200мс, после чего скидывается. Это обусловлено тем, что если мы будем хранить состояние пульта то возможна ситуация, когда свет включили одним пультом, а выключили другим (например напрямую в HomeAssistance). В этом случае для пульта по прежнему будет состояние "включено", и соответственно, повторно включить свет через него уже не получиться. Надо будет сначала его "выключить", и только потом можно будет включить. 

К сожалению код работы с пультами не мой, я его только адаптировал при изменениях. У меня же пульты взаимодействуют с модулями напрямую, поэтому на практике мне настраивать связь пульт+модуль не доводилось. Я постараюсь на этой неделе перепроверить работоспособность кода для работы с пультами и написать пример настройки по связи между пультами и модулями.

**Comment by SergejPr** [comment]
Залил новую версию. Переработал сенсоры и протестировал их. Вроде как все работает. 

Кроме того добавил noolite службы, так что теперь через них можно дергать почти все управляющие команды которые поддерживает модуль. Но есть одно но с noolite модулями (без обратной связи). Вызов некоторых служб может привести к некорректному состоянию, так как мы не знаем конечное состояние после выполнения, а запросить его не можем. Например при изменение яркости вниз при достижении 0 модуль выключается, но в системе он останется включенным, так как мы не знаем на какой яркости остановились и узнать не можем. 

В некоторых случаях пульт присылает двойную команду: при нажатии и удержании кнопки прилетает стартовая команда, а при отпускании стоповая. Соответственно сенсоры так же пришлют двойное состояние. Например: tune_up - tune_stop. В целом состояния мелькают на экране, но при необходимости можно установить уровень логирования в DEBUG и тогда их можно будет посмотреть в логах. Для этого в файле `custom_components/noolite/const.py` заменить `logging.WARNING` на `logging.DEBUG` в строке

```
LOG_LEVEL = logging.WARNING
```

Связь между сенсорами и модулями можно сделать через автоматизации. Пример в файле automations.yaml. Возможные состояние сенсоров описаны в readme.

**!!!NOTE** Возможно придется обновить и сам HA до последней версии. На версии примерно полугодовой давности точно не работает.

**Comment by eratnik** [comment]
Спасибо за доработки! Сегодня попробовал обновиться, но после перезагрузки в логе ошибки и од на из двух сущностей света недоступна (почему-то если указать mode: noolite, то даже в панели разработчика ее нет).
```
Logger: homeassistant.components.light
Source: helpers/entity.py:940
Integration: Освещение (documentation, issues)
First occurred: 14:50:47 (3 occurrences)
Last logged: 14:50:48

Error adding entities for domain light with platform noolite
Error while setting up noolite platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 613, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 748, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 505, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 511, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 935, in state
    return STATE_ON if self.is_on else STATE_OFF
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 940, in is_on
    return self._attr_is_on
AttributeError: 'NooLiteSwitch' object has no attribute '_attr_is_on'

```

**Comment by eratnik** [comment]
> Залил новую версию. Переработал сенсоры и протестировал их. Вроде как все работает.
> 
> Кроме того добавил noolite службы, так что теперь через них можно дергать почти все управляющие команды которые поддерживает модуль. Но есть одно но с noolite модулями (без обратной связи). Вызов некоторых служб может привести к некорректному состоянию, так как мы не знаем конечное состояние после выполнения, а запросить его не можем. Например при изменение яркости вниз при достижении 0 модуль выключается, но в системе он останется включенным, так как мы не знаем на какой яркости остановились и узнать не можем.
> 
> В некоторых случаях пульт присылает двойную команду: при нажатии и удержании кнопки прилетает стартовая команда, а при отпускании стоповая. Соответственно сенсоры так же пришлют двойное состояние. Например: tune_up - tune_stop. В целом состояния мелькают на экране, но при необходимости можно установить уровень логирования в DEBUG и тогда их можно будет посмотреть в логах. Для этого в файле `custom_components/noolite/const.py` заменить `logging.WARNING` на `logging.DEBUG` в строке
> 
> ```
> LOG_LEVEL = logging.WARNING
> ```
> 
> Связь между сенсорами и модулями можно сделать через автоматизации. Пример в файле automations.yaml. Возможные состояние сенсоров описаны в readme.
> 
> **!!!NOTE** Возможно придется обновить и сам HA до последней версии. На версии примерно полугодовой давности точно не работает.

Прошу меня простить, был на предпоследней версии, видимо, из-за нее и были ошибки. Обновился - силовые блоки работают. Пульты буду еще тестировать.
Спасибо

**Comment by SergejPr** [comment]
> Прошу меня простить, был на предпоследней версии, видимо, из-за нее и были ошибки. Обновился - силовые блоки работают. Пульты буду еще тестировать.
> Спасибо

Ни чего страшного :)

**Comment by SergejPr** [comment]
Ради интереса, а на какой версии вы были? Просто на выходных была еще 2022.2.3 и на ней все прекрасно работало, а сейчас уже версия 2022.2.5, причем она вышла сегодня, а предыдущая версия 2022.2.4 вышла вчера.

**Comment by eratnik** [comment]
> Ради интереса, а на какой версии вы были? Просто на выходных была еще 2022.2.3 и на ней все прекрасно работало, а сейчас уже версия 2022.2.5, причем она вышла сегодня, а предыдущая версия 2022.2.4 вышла вчера.

Я на 2022.2.4 не успел обновиться и слава богу, т.к. ее отозвали. Нет, под предыдущей я имел в виду  2022.2.0 (вроде оно по памяти, последнее январское обновление).
Кстати, вчера потестировал пульты - не работают они у меня, но мне уже кажется, что дело тут не в интеграции, а в самих пультах. Я общался в чате поддержки в телеграм и выяснилось, что мой один пульт вообще не привязывается, т.к. частоты не совпадают со стиком, а второй привязался, но не работает(( Видимо, заменить пульты на что-то более интегрируемое.

**Comment by SergejPr** [comment]
А как определили что не работает? Через официальную программу NooLite ONE? Как вариант попробовать сбиндить модуль и пульт напрямую.

**Comment by eratnik** [comment]
> А как определили что не работает? Через официальную программу NooLite ONE? Как вариант попробовать сбиндить модуль и пульт напрямую.

Они напрямую пульт к силовому блоку легко сопрягаются, а вот к mtrf-64 привязался только один пульт, а второй ни в какую (я по этому случаю видио снимал и поддержке кидал, они сказали, что частоты mtrf-64 чуть отличаются от силовых блоков, у последних более чувствительный приемник вроде; предложили прислать им, чтобы они поправили). Второй привязался, я его прописал в HA, но в нем статус не меняется - состояние постоянно "unknown" и все.  
В NooLite ONE с периодическими пропусками принимает команды от привязавшегося пульта.

**Comment by SergejPr** [comment]
Если NooLite ONE принимает команды, пусть и с пропусками то и в HA они должны долетать.
 
Посмотрел журналы у себя в тестовом - там действительно не показывает состояний почему-то:
![Снимок экрана 2022-02-10 в 14 26 24](https://user-images.githubusercontent.com/8930167/153400287-f8fa9497-ee2e-4a62-90a1-5cc388220d08.png)

Но при этом в истории вроде норм показывает:
![Снимок экрана 2022-02-10 в 14 27 44](https://user-images.githubusercontent.com/8930167/153400305-b6a98e5d-a23c-4a49-9c60-188d092ca9b7.png)

Попробуйте включить  установить уровень логирования в DEBUG и тогда их можно будет посмотреть в логах. Для этого в файле custom_components/noolite/const.py заменить logging.WARNING на logging.DEBUG в строке
```
LOG_LEVEL = logging.WARNING
```
и перезапустить HA. Тогда в системе в журнале сервера события от пультов должны будут залогироваться:

![Снимок экрана 2022-02-10 в 14 29 17](https://user-images.githubusercontent.com/8930167/153400356-f27060b7-be01-41d6-a617-c7bfddf4e1d9.png)
