### ISSUE TITLE
добавить в настройки скорость порта

### ISSUE THREAD

**Issue by waliko** [SergejPr/HomeAssistance-NooLite#16]
можно ли вынести в конфиг насктройку для скорость порта?
(noolite выдал прошивку для mtrf увеличивающую скорость до 115200)

спасибо!

**Comment by SergejPr** [comment]
Добрый вечер. Сделано. 

P.S. А не могли бы вы поделиться прошивкой или дать ссылку на нее? А то на сайте не нашел. Спасибо.

**Comment by waliko** [comment]
Добрый день,
и вам спасибо за оперативность!

прошивку приложил, шить из noolite one (вернуть назад скорость пока нельзя, нет прошивки понижающей скорость, и noolite one перестанет видить адаптер, но на гите есть исходники noolite one. там можно добавить нужную скорость и скомпилировать)

[https://t.me/Noolite](https://t.me/Noolite) - заодно ссылочку на канал любителей noolite оставлю =) (тут люди подняли вопрос про скорость и производитель любезно выдал прошивку)

[MTRF-64_115200baud.bin.zip](https://github.com/SergejPr/HomeAssistance-NooLite/files/8423901/MTRF-64_115200baud.bin.zip)
