### ISSUE TITLE
Problem while starting HA

### ISSUE THREAD

**Issue by donatelloth** [SergejPr/HomeAssistance-NooLite#3]
While starting HA this error is being put in the log:

```
Dec 05 07:51:35 raspberrypi hass[18218]: 2018-12-05 07:51:35 ERROR (MainThread) [homeassistant.setup] Error during setup of component NooLite
Dec 05 07:51:35 raspberrypi hass[18218]: Traceback (most recent call last):
Dec 05 07:51:35 raspberrypi hass[18218]:   File "/usr/local/lib/python3.5/dist-packages/homeassistant/setup.py", line 148, in _async_setup_component
Dec 05 07:51:35 raspberrypi hass[18218]:     component.setup, hass, processed_config)  # type: ignore
Dec 05 07:51:35 raspberrypi hass[18218]:   File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
Dec 05 07:51:35 raspberrypi hass[18218]:     yield self  # This tells Task to wait for completion.
Dec 05 07:51:35 raspberrypi hass[18218]:   File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
Dec 05 07:51:35 raspberrypi hass[18218]:     future.result()
Dec 05 07:51:35 raspberrypi hass[18218]:   File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
Dec 05 07:51:35 raspberrypi hass[18218]:     raise self._exception
Dec 05 07:51:35 raspberrypi hass[18218]:   File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
Dec 05 07:51:35 raspberrypi hass[18218]:     result = self.fn(*self.args, **self.kwargs)
Dec 05 07:51:35 raspberrypi hass[18218]:   File "/home/pi/.homeassistant/custom_components/NooLite.py", line 46, in setup
Dec 05 07:51:35 raspberrypi hass[18218]:     from NooLite_F.MTRF64 import MTRF64Controller
Dec 05 07:51:35 raspberrypi hass[18218]:   File "/home/pi/.homeassistant/deps/lib/python3.5/site-packages/NooLite_F/__init__.py", line 1, in <module>
Dec 05 07:51:35 raspberrypi hass[18218]:     from NooLite_F.NooLiteFController import NooLiteFController, Direction, RemoteControllerListener, BatteryState, ModuleMode
Dec 05 07:51:35 raspberrypi hass[18218]:   File "/home/pi/.homeassistant/deps/lib/python3.5/site-packages/NooLite_F/NooLiteFController.py", line 46
Dec 05 07:51:35 raspberrypi hass[18218]:     dimmer_mode: bool = None
Dec 05 07:51:35 raspberrypi hass[18218]:                ^
Dec 05 07:51:35 raspberrypi hass[18218]: SyntaxError: invalid syntax
```

**Home Assistant**: 0.83.2
**Python Version**: 3.5

This causing not starting the component at all.

**Comment by SergejPr** [comment]
Update main NooLite-F module to support Python 3.5.

**Comment by donatelloth** [comment]
@SergejPr thank you very much.

Just updated to last versions of plugins.
But know i get new error while starting the HA:

> Dec 10 21:24:19 raspberrypi hass[4333]: 2018-12-10 21:24:19 ERROR (MainThread) [homeassistant.setup] Error during setup of component NooLite
Dec 10 21:24:19 raspberrypi hass[4333]: Traceback (most recent call last):
Dec 10 21:24:19 raspberrypi hass[4333]:   File "/usr/local/lib/python3.5/dist-packages/homeassistant/setup.py", line 148, in _async_setup_component
Dec 10 21:24:19 raspberrypi hass[4333]:     component.setup, hass, processed_config)  # type: ignore
Dec 10 21:24:19 raspberrypi hass[4333]:   File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
Dec 10 21:24:19 raspberrypi hass[4333]:     yield self  # This tells Task to wait for completion.
Dec 10 21:24:19 raspberrypi hass[4333]:   File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
Dec 10 21:24:19 raspberrypi hass[4333]:     future.result()
Dec 10 21:24:19 raspberrypi hass[4333]:   File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
Dec 10 21:24:19 raspberrypi hass[4333]:     raise self._exception
Dec 10 21:24:19 raspberrypi hass[4333]:   File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
Dec 10 21:24:19 raspberrypi hass[4333]:     result = self.fn(*self.args, **self.kwargs)
Dec 10 21:24:19 raspberrypi hass[4333]:   File "/home/pi/.homeassistant/custom_components/NooLite.py", line 50, in setup
Dec 10 21:24:19 raspberrypi hass[4333]:     DEVICE = MTRF64Controller(config[DOMAIN].get(CONF_PORT))
Dec 10 21:24:19 raspberrypi hass[4333]: KeyError: 'NooLite'

**Comment by SergejPr** [comment]
@donatelloth As I see, you use RasberryPi. Could you please provide me info about your hradware configuration:
- which RasberryPi do you use?
- which NooLite module do you use (e.g. MTRF64, MTRF64USB, etc)?

It can be also helpfull if you can send your HA config.

**Comment by SergejPr** [comment]
@donatelloth 
I can reproduce this issue. It is related that you are missed NooLite part in HA configuration, or you use incorrect keyword for it. The keyword is case sensitive and should be `NooLite`, not `noolite`.

I will make a fix for this to allows use a case insensetive keyword or miss noolite part.

**Comment by donatelloth** [comment]
Yeah, of course.

> which RasberryPi do you use?

Raspberry Pi 3B, raspbian stretch
> which NooLite module do you use (e.g. MTRF64, MTRF64USB, etc)?

MTRF64 on /dev/ttyS0, so i changed in Noolite.py one stroke to:
`DEFAULT_PORT = '/dev/ttyS0'`
> It can be also helpfull if you can send your HA config.

So this is the configuration:
```  
- platform: NooLite
    channel: 0
    name: "living_room_light"
    scan_interval: 60
    type: Dimmer
    mode: NooLite-F
```

**Comment by donatelloth** [comment]
> I can reproduce this issue. It is related that you are missed NooLite part in HA configuration, or you use incorrect keyword for it. The keyword is case sensitive and should be NooLite, not noolite.

@SergejPr this is strange because i just copied the following from examples and paste it to the "light" domain. The full block of light is:
```
light:
- platform: NooLite
    channel: 0
    name: "living_room_light"
    scan_interval: 60
    type: Dimmer
    mode: NooLite-F
```

**Comment by SergejPr** [comment]
Try to add followed part in your config file, as it is in my example config:
```
NooLite:
  port: "/dev/ttyS0"
```

**Comment by donatelloth** [comment]
> Try to add followed part in your config file, as it is in my example config:

Oh, I really missed it. I'm giving a try.

**Comment by donatelloth** [comment]
That worked. Thank you.

**Comment by SergejPr** [comment]
**Just a note:** because you changed the default port in NooLite.py, you can miss port parameter in your config and just use:
```
NooLite:
```
